apiVersion: v1
kind: ConfigMap
metadata:
  name: build-dockerfile
  namespace: nginx
data:
  Dockerfile: |

      # Use Red Hat Universal Base Image 9 Micro
      FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

      # Install necessary packages
      USER root
      RUN microdnf install nginx -y \
          && microdnf clean all \
          && rm -f /etc/nginx/nginx.conf \
          && mkdir -p /usr/share/nginx/html \
          && mkdir -p /var/cache/nginx \
          && chown -R 1001:0 /usr/share/nginx/html \
          && chown -R 1001:0 /var/cache/nginx \
          && chown -R 1001:0 /var/log/nginx \
          && chown -R 1001:0 /etc/nginx \
          && chmod -R g=u /usr/share/nginx/html \
          && chmod -R g=u /var/cache/nginx \
          && chmod -R g=u /var/log/nginx \
          && chmod -R g=u /etc/nginx
      WORKDIR /workspace/source/mginx
      # Copy a new configuration file from your context into the container
      COPY nginx.conf /etc/nginx/nginx.conf
      COPY html/ /usr/share/nginx/html/

      # Switch to non-root user
      USER 1001

      # Expose port 8080 for the web server (port 80 is typically reserved for root)
      EXPOSE 8080

      # Update nginx.conf to listen on port 8080 and adjust permissions
      RUN sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/nginx.conf \
          && sed -i 's/user nginx;/user 1001;/' /etc/nginx/nginx.conf

      # Start Nginx when the container launches
      CMD ["nginx", "-g", "daemon off;"]
