apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:

  labels:
    app: app
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: nginx
  
  name: app
  namespace: nginx
spec:
  lookupPolicy:
    local: false
