apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nginx
  name: nginx-ubi-min-build-workspace
  namespace: nginx
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  
